# Generated by Django 3.2.7 on 2021-12-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('A', 'Simple Modification - Make from Scratch'), ('B', 'Minor Mod to Standard Device'), ('C', 'Complex Design - Requires Predicate'), ('D', 'Complex Assembly - Many Components')], max_length=1, null=True),
        ),
    ]
