# Generated by Django 3.2.7 on 2021-12-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.CharField(choices=[('A', '1.9 Inch Ball w/ Impact Cap'), ('B', '4.8 Inch Ergonomic Inline'), ('C', '4.75 Inch Tapered w/ Impact Cap'), ('D', '6 Inch Ergonomic Inline w/ Impact Cap'), ('E', '4 Inch Cervical Inline w/Impact Cap')], max_length=1, null=True),
        ),
    ]
