# Generated by Django 3.2.7 on 2021-12-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='part_number',
            field=models.CharField(default='X0000000', max_length=360),
        ),
    ]
