# Generated by Django 3.2.7 on 2021-12-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CT', 'Cervical/Trauma'), ('IFAVBR', 'Interbody Fusion and Vertebral Body Replacement'), ('TC', 'Thoracolumbar'), ('MAST', 'MAST'), ('GI', 'General Instruments')], max_length=6, null=True),
        ),
    ]
