# Generated by Django 3.2.7 on 2021-12-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
