# Generated by Django 3.2.7 on 2021-12-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20211202_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.CharField(choices=[('A', '1.9 Inch Ball w/ Impact Cap'), ('B', '4.8 Inch Ergonomic Inline'), ('C', '4.75 Inch Tapered w/ Impact Cap'), ('D', '6 Inch Ergonomic Inline w/ Impact Cap'), ('E', '4 Inch Cervical Inline w/Impact Cap'), ('NP', 'New Product'), ('NA', 'Not Applicable')], max_length=2, null=True),
        ),
    ]
