# Generated by Django 3.2.7 on 2021-12-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cervical/Trauma', 'Cervical/Trauma'), ('Interbody Fusion and Vertebral Body Replacement', 'Interbody Fusion and Vertebral Body Replacement'), ('Thoracolumbar', 'Thoracolumbar'), ('MAST', 'MAST'), ('General Instruments', 'General Instruments'), ('New Product', 'New Product')], max_length=47, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.CharField(choices=[('1.9 Inch Ball w/ Impact Cap', '1.9 Inch Ball w/ Impact Cap'), ('4.8 Inch Ergonomic Inline', '4.8 Inch Ergonomic Inline'), ('4.75 Inch Tapered w/ Impact Cap', '4.75 Inch Tapered w/ Impact Cap'), ('6 Inch Ergonomic Inline w/ Impact Cap', '6 Inch Ergonomic Inline w/ Impact Cap'), ('4 Inch Cervical Inline w/Impact Cap', '4 Inch Cervical Inline w/Impact Cap'), ('New Product', 'New Product'), ('Not Applicable', 'Not Applicable')], max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Simple Modification - Make from Scratch', 'Simple Modification - Make from Scratch'), ('Minor Mod to Standard Device', 'Minor Mod to Standard Device'), ('Complex Design - Requires Predicate', 'Complex Design - Requires Predicate'), ('Complex Assembly - Many Components', 'Complex Assembly - Many Components'), ('New Product', 'New Product')], max_length=39, null=True),
        ),
    ]
