# Generated by Django 3.2.7 on 2021-11-17 01:51

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211007_2107'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateOrderView',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            bases=(django.views.generic.edit.CreateView, 'products.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_reordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='num_reorders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='parent_reorder',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
