# Generated by Django 3.2.7 on 2021-12-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211118_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='disclaimer',
            field=models.BooleanField(help_text='I agree to submit this request form to my manager for approval.  If actual cost exceeds maximum price range, I will be notified with adjusted price prior to manufacturing with no obligation to continue.'),
        ),
    ]
