# Generated by Django 3.2.7 on 2021-12-03 03:52

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_disclaimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='disclaimer',
            field=models.BooleanField(help_text='I agree to submit this request form to my manager for approval.  If actual cost exceeds maximum price range, I will be notified with adjusted price prior to manufacturing with no obligation to continue.', validators=[orders.models.Order.validate_true]),
        ),
    ]
