# Generated by Django 3.2.7 on 2021-10-17 22:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_auto_20211007_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SR_first_name', models.CharField(max_length=35)),
                ('SR_last_name', models.CharField(max_length=35)),
                ('SR_phone_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('SM_first_name', models.CharField(max_length=35)),
                ('SM_last_name', models.CharField(max_length=35)),
                ('SR_email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=20)),
                ('physician', models.CharField(max_length=70)),
                ('hospital', models.CharField(max_length=70)),
                ('customer_type', models.CharField(choices=[('CURRENT', 'Current'), ('NEW', 'New'), ('CONVERSION', 'Conversion')], default='CURRENT', max_length=10)),
                ('clinical_need', models.CharField(max_length=200)),
                ('instrument_category', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField()),
                ('disclaimer', models.BooleanField()),
                ('instrument_type', models.CharField(max_length=270)),
                ('instrument_handle', models.CharField(max_length=270)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('IN PROGRESS', 'In Progress'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=11)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
