# Generated by Django 3.2.7 on 2021-11-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20211007_2107'),
        ('orders', '0002_auto_20211111_1901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateOrderView',
            new_name='OrderFromCatalog',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_reorder',
            new_name='is_reordered',
        ),
    ]
