# Generated by Django 3.2.9 on 2021-11-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211117_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='denial_reason',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='CreateOrderView',
        ),
    ]
