# Generated by Django 3.2.7 on 2021-11-15 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_sr_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='SR_phone_number',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
