# Generated by Django 3.2.7 on 2021-11-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211115_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='disclaimer',
            field=models.BooleanField(null=True),
        ),
    ]
