# Generated by Django 3.2.7 on 2021-12-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(default='Standard', max_length=120),
        ),
    ]
