# Generated by Django 3.2.7 on 2021-11-15 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_disclaimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='SR_phone_number',
            field=models.PositiveIntegerField(default=5555555555, validators=[django.core.validators.MaxValueValidator(9999999999)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='disclaimer',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
