# Generated by Django 3.2.7 on 2021-12-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_disclaimer'),
        ('orders', '0007_auto_20211203_0513'),
    ]

    operations = [
    ]
